/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADirectoryTree: typeof import('ant-design-vue/es')['DirectoryTree']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARow: typeof import('ant-design-vue/es')['Row']
    ArrowDownOutlined: typeof import('@ant-design/icons-vue')['ArrowDownOutlined']
    ArrowUpOutlined: typeof import('@ant-design/icons-vue')['ArrowUpOutlined']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    CloseOutlined: typeof import('@ant-design/icons-vue')['CloseOutlined']
    DeleteOutlined: typeof import('@ant-design/icons-vue')['DeleteOutlined']
    DownOutlined: typeof import('@ant-design/icons-vue')['DownOutlined']
    IconButton: typeof import('./../components/IconButton/index.vue')['default']
    MenuItem: typeof import('./../components/MeuTabs/MenuItem.vue')['default']
    MeuTabs: typeof import('./../components/MeuTabs/index.vue')['default']
    PlusOutlined: typeof import('@ant-design/icons-vue')['PlusOutlined']
    ReloadOutlined: typeof import('@ant-design/icons-vue')['ReloadOutlined']
    SearchOutlined: typeof import('@ant-design/icons-vue')['SearchOutlined']
    SwapOutlined: typeof import('@ant-design/icons-vue')['SwapOutlined']
    SwitcherOutlined: typeof import('@ant-design/icons-vue')['SwitcherOutlined']
    VerticalAlignTopOutlined: typeof import('@ant-design/icons-vue')['VerticalAlignTopOutlined']
  }
}
